# 头部菜单，title: link
menu:
  Whoami: /whoami
  Github: https://github.com/chrisgou
  分类: /categories
  归档: /archives
  标签云: /tags

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
  - http://link.hhtjim.com/163/5146554.mp3
  - http://link.hhtjim.com/qq/001faIUs4M2zna.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: # /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: 'e992ba2640b7128233d4'
    # 应用秘钥
    clientSecret: 'fdd0d3dc62028cf293522b04b6e2a1c57015d0e1'
    # issue仓库名
    repo: 'blog'
    # Github名
    owner: 'chrisgou'
    # Github名
    admin: ['chrisgou']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: chrisgou 博客 hexo 前端 全栈 vue node

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
